gateway_base: https://aia.gateway.dell.com/genai/dev/v1
token_mode: aia_auth
aia_access_token: ''
client_id: 
host: eos2git.cec.lab.emc.com
org: ISG-Edge
client_secret: 
scope: ''
github_token: 
enable_pki_zip_patch: false
pki_zip_url: ''
pki_pems:
- Dell Technologies Root Certificate Authority 2018.pem
- Dell Technologies Issuing CA 101_new.pem
custom_ca_bundle: ''
model: llama-3-3-70b-instruct
correlation_id: ISG
output_format: html
selected_models:
- llama-3-3-70b-instruct
- mixtral-8x7b-instruct-v01
- mistral-7b-instruct-v03
- mistral-7b-instruct-v03-fc
- mistral-small-3.1-24b-instruct-2503
- llama-3-8b-instruct
- llama-3-1-8b-instruct
- llama-3-2-3b-instruct
- llama-3-3-nemotron-super-49b-v1
- phi-3-mini-128k-instruct
- phi-3-5-moe-instruct
- gemma-3-27b-it
- codellama-13b-instruct
- gpt-oss-120b
- gpt-oss-20b
parallel_models: true
skip_generated: true
generated_path_globs:
- '**/generated/**'
- '**/gen/**'
- '**/autogen/**'
- '**/build/**'
- '**/out/**'
- '**/dist/**'
generated_file_regex: (?:^|/)(?:.*\bgenerated\b.*|.*_pb2\.py|.*\.g\.cs|.*\.Designer\.cs|.*\.swagger\.ts|.*\.pb\.go|.*\.g\.dart|.*\.g\.ts)$
generated_header_markers:
- Code generated by
- Automatically generated
- Auto-generated
- DO NOT EDIT
- '@generated'
